import type { Metadata } from "next";
import { Nunito } from "next/font/google"; // Import Lora font
import "./globals.css";
import Header from "@/components/Header";

const nunito = Nunito({
  subsets: ['latin'], // Specify the subsets you need
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'], // Choose weights as needed
  variable: '--font-nunito', // Optional: Define a variable for CSS
});

export const metadata: Metadata = {
  title: "EasyTransport Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} antialiased`}
      >
        <div className="min-h-screen flex flex-col">
            <Header />
            <main className="bg-slate-800">
              {children}  
            </main>
        </div>
      </body>
    </html>
  );
}
